### ISSUE TITLE
latin not greek ?

### ISSUE THREAD

**Issue by yaaax** [martignoni/hugo-loremipsum#1]
Hi there,
Thanks for this useful module!

One little detail, I think Lorem Ipsum is -pseudo- latin, so not "greek text" as mentioned in the Readme file.
Alternatively, we can use the term [greeking](https://en.wikipedia.org/wiki/Greeking) _(just found this one, I didn't know!)_

All the best

**Comment by martignoni** [comment]
Thanks for your words. Yes, Lorem ipsum is pseudo-latin indeed.

The expression in the README is an allusion to the process of greeking you mention and to the english expression: [That's Greek to me](https://en.wikipedia.org/wiki/Greek_to_me).
